{% set name = "Soprano" %}
{% set version = "0.8.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CCP-NC/soprano/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e99defb57c4338d5a1636a6bdb26a5d986694ba51ab16dcda9d53ab4c5d26d68
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - vasp2cell = soprano.scripts.vasp2cell:__main__
    - soprano_submitter = soprano.hpc.submitter:__main__
    - phylogen = soprano.scripts.phylogen:__main__
    - magresaverage = soprano.scripts.msaverage:__main__

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - ase

test:
  imports:
    - soprano
    - soprano.analyse
    - soprano.calculate
    - soprano.collection
    - soprano.data
    - soprano.hpc
    - soprano.nmr
    - soprano.properties
    - soprano.measure
    - soprano.optional
    - soprano.rnd
    - soprano.selection
    - soprano.utils

about:
  home: https://ccp-nc.github.io/soprano/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'A Python library to crack crystals'
  description: |
    Soprano is a Python library developed and maintained by the CCP for NMR
    Crystallography as a tool to help scientists working with crystallography and
    simulations to generate, manipulate, run calculations on and analyse large
    data sets of crystal structures, with a particular attention to the output of
    ab-initio random structure searching,
    or AIRSS. (https://www.mtg.msm.cam.ac.uk/Codes/AIRSS)

    It provides a number of functionalities to help automate many common tasks
    in computational crystallography.
  doc_url: https://ccp-nc.github.io/soprano/sphinx/html/index.html
  dev_url: https://github.com/CCP-NC/soprano

extra:
  recipe-maintainers:
    - stur86
